//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApplication.DaoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DaoServiceReference.SaleDaoServiceSoap")]
    public interface SaleDaoServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strSale 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveSale", ReplyAction="*")]
        SalesApplication.DaoServiceReference.SaveSaleResponse SaveSale(SalesApplication.DaoServiceReference.SaveSaleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveSaleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveSale", Namespace="http://tempuri.org/", Order=0)]
        public SalesApplication.DaoServiceReference.SaveSaleRequestBody Body;
        
        public SaveSaleRequest() {
        }
        
        public SaveSaleRequest(SalesApplication.DaoServiceReference.SaveSaleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveSaleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSale;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strProduct;
        
        public SaveSaleRequestBody() {
        }
        
        public SaveSaleRequestBody(string strSale, string strProduct) {
            this.strSale = strSale;
            this.strProduct = strProduct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveSaleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveSaleResponse", Namespace="http://tempuri.org/", Order=0)]
        public SalesApplication.DaoServiceReference.SaveSaleResponseBody Body;
        
        public SaveSaleResponse() {
        }
        
        public SaveSaleResponse(SalesApplication.DaoServiceReference.SaveSaleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveSaleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SaveSaleResult;
        
        public SaveSaleResponseBody() {
        }
        
        public SaveSaleResponseBody(bool SaveSaleResult) {
            this.SaveSaleResult = SaveSaleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SaleDaoServiceSoapChannel : SalesApplication.DaoServiceReference.SaleDaoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaleDaoServiceSoapClient : System.ServiceModel.ClientBase<SalesApplication.DaoServiceReference.SaleDaoServiceSoap>, SalesApplication.DaoServiceReference.SaleDaoServiceSoap {
        
        public SaleDaoServiceSoapClient() {
        }
        
        public SaleDaoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SaleDaoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaleDaoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaleDaoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SalesApplication.DaoServiceReference.SaveSaleResponse SalesApplication.DaoServiceReference.SaleDaoServiceSoap.SaveSale(SalesApplication.DaoServiceReference.SaveSaleRequest request) {
            return base.Channel.SaveSale(request);
        }
        
        public bool SaveSale(string strSale, string strProduct) {
            SalesApplication.DaoServiceReference.SaveSaleRequest inValue = new SalesApplication.DaoServiceReference.SaveSaleRequest();
            inValue.Body = new SalesApplication.DaoServiceReference.SaveSaleRequestBody();
            inValue.Body.strSale = strSale;
            inValue.Body.strProduct = strProduct;
            SalesApplication.DaoServiceReference.SaveSaleResponse retVal = ((SalesApplication.DaoServiceReference.SaleDaoServiceSoap)(this)).SaveSale(inValue);
            return retVal.Body.SaveSaleResult;
        }
    }
}
